"use client";

import { useRef } from "react";
import { Button } from "@/components/ui/button";
import { Download } from "lucide-react";

interface Transaction {
  amount: number;
  type: "income" | "expense";
  category: string;
  description: string;
  date: string;
}

interface Budget {
  category: string;
  subtype: string | null;
  limit_amount: number;
  spent_amount: number;
}

interface Goal {
  title: string;
  targetAmount: number;
  currentAmount: number;
  status: string;
}

interface MonthlyReportProps {
  month: string; // e.g. "January 2026"
  transactions: Transaction[];
  budgets: Budget[];
  goals: Goal[];
  userName?: string;
}

function formatINR(amount: number) {
  return new Intl.NumberFormat("en-IN", {
    style: "currency",
    currency: "INR",
    maximumFractionDigits: 0,
  }).format(amount);
}

export function MonthlyReportDownloadButton(props: MonthlyReportProps) {
  const ref = useRef<HTMLDivElement>(null);

  const handleDownload = () => {
    const el = ref.current;
    if (!el) return;

    const printWindow = window.open("", "_blank");
    if (!printWindow) return;

    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
      <head>
        <title>Financial Report — ${props.month}</title>
        <style>
          * { margin: 0; padding: 0; box-sizing: border-box; }
          body { font-family: system-ui, sans-serif; color: #111; background: white; padding: 32px; font-size: 13px; }
          h1 { font-size: 22px; font-weight: 700; margin-bottom: 4px; }
          h2 { font-size: 15px; font-weight: 600; margin: 20px 0 8px; border-bottom: 1px solid #e5e7eb; padding-bottom: 4px; }
          .subtitle { color: #6b7280; font-size: 12px; margin-bottom: 20px; }
          .grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 12px; margin-bottom: 20px; }
          .card { border: 1px solid #e5e7eb; border-radius: 8px; padding: 12px; }
          .card .label { font-size: 11px; color: #6b7280; }
          .card .value { font-size: 18px; font-weight: 700; margin-top: 2px; }
          .income { color: #16a34a; }
          .expense { color: #dc2626; }
          table { width: 100%; border-collapse: collapse; font-size: 12px; }
          th { text-align: left; padding: 6px 8px; background: #f9fafb; border-bottom: 1px solid #e5e7eb; font-weight: 600; color: #374151; }
          td { padding: 6px 8px; border-bottom: 1px solid #f3f4f6; }
          .progress-bar { background: #f3f4f6; border-radius: 4px; height: 6px; width: 100%; }
          .progress-fill { height: 6px; border-radius: 4px; }
          .over { background: #ef4444; }
          .warn { background: #f59e0b; }
          .ok { background: #22c55e; }
          .badge { display: inline-block; padding: 2px 8px; border-radius: 9999px; font-size: 10px; font-weight: 600; }
          .badge-active { background: #dbeafe; color: #1d4ed8; }
          .badge-completed { background: #dcfce7; color: #15803d; }
          .badge-overdue { background: #fee2e2; color: #dc2626; }
          footer { margin-top: 32px; padding-top: 12px; border-top: 1px solid #e5e7eb; font-size: 11px; color: #9ca3af; }
        </style>
      </head>
      <body>
        ${el.innerHTML}
        <footer>Generated by Expense Tracker · ${new Date().toLocaleDateString("en-IN")}</footer>
        <script>window.onload = () => { window.print(); }<\/script>
      </body>
      </html>
    `);
    printWindow.document.close();
  };

  const income = props.transactions
    .filter((t) => t.type === "income")
    .reduce((s, t) => s + t.amount, 0);
  const expenses = props.transactions
    .filter((t) => t.type === "expense")
    .reduce((s, t) => s + t.amount, 0);
  const balance = income - expenses;

  const categoryBreakdown = props.transactions
    .filter((t) => t.type === "expense")
    .reduce<Record<string, number>>((acc, t) => {
      acc[t.category] = (acc[t.category] || 0) + t.amount;
      return acc;
    }, {});

  const top5Transactions = [...props.transactions]
    .sort((a, b) => b.amount - a.amount)
    .slice(0, 5);

  return (
    <>
      {/* Hidden render target */}
      <div className="hidden">
        <div ref={ref}>
          <h1>Financial Report</h1>
          <p className="subtitle">{props.month}{props.userName ? ` · ${props.userName}` : ""}</p>

          {/* Summary */}
          <div className="grid">
            <div className="card">
              <div className="label">Total Income</div>
              <div className="value income">{formatINR(income)}</div>
            </div>
            <div className="card">
              <div className="label">Total Expenses</div>
              <div className="value expense">{formatINR(expenses)}</div>
            </div>
            <div className="card">
              <div className="label">Net Balance</div>
              <div className={`value ${balance >= 0 ? "income" : "expense"}`}>{formatINR(balance)}</div>
            </div>
          </div>

          {/* Expense by category */}
          <h2>Expense by Category</h2>
          <table>
            <thead>
              <tr>
                <th>Category</th>
                <th>Amount</th>
                <th>% of Expenses</th>
              </tr>
            </thead>
            <tbody>
              {Object.entries(categoryBreakdown)
                .sort(([, a], [, b]) => b - a)
                .slice(0, 10)
                .map(([cat, amt]) => (
                  <tr key={cat}>
                    <td>{cat}</td>
                    <td>{formatINR(amt)}</td>
                    <td>{expenses > 0 ? ((amt / expenses) * 100).toFixed(1) : 0}%</td>
                  </tr>
                ))}
            </tbody>
          </table>

          {/* Budget performance */}
          {props.budgets.length > 0 && (
            <>
              <h2>Budget Performance</h2>
              <table>
                <thead>
                  <tr>
                    <th>Budget</th>
                    <th>Limit</th>
                    <th>Spent</th>
                    <th>Status</th>
                  </tr>
                </thead>
                <tbody>
                  {props.budgets.map((b, i) => {
                    const pct = b.limit_amount > 0 ? (b.spent_amount / b.limit_amount) * 100 : 0;
                    const statusClass = pct > 100 ? "over" : pct > 80 ? "warn" : "ok";
                    return (
                      <tr key={i}>
                        <td>{b.category}{b.subtype ? ` / ${b.subtype}` : ""}</td>
                        <td>{formatINR(b.limit_amount)}</td>
                        <td>{formatINR(b.spent_amount)}</td>
                        <td>
                          <div className="progress-bar">
                            <div
                              className={`progress-fill ${statusClass}`}
                              style={{ width: `${Math.min(100, pct)}%` }}
                            />
                          </div>
                          <span style={{ fontSize: 10, color: "#6b7280" }}>{pct.toFixed(0)}%</span>
                        </td>
                      </tr>
                    );
                  })}
                </tbody>
              </table>
            </>
          )}

          {/* Top transactions */}
          {top5Transactions.length > 0 && (
            <>
              <h2>Top Transactions</h2>
              <table>
                <thead>
                  <tr>
                    <th>Date</th>
                    <th>Description</th>
                    <th>Category</th>
                    <th>Amount</th>
                    <th>Type</th>
                  </tr>
                </thead>
                <tbody>
                  {top5Transactions.map((t, i) => (
                    <tr key={i}>
                      <td>{t.date}</td>
                      <td>{t.description}</td>
                      <td>{t.category}</td>
                      <td>{formatINR(t.amount)}</td>
                      <td style={{ color: t.type === "income" ? "#16a34a" : "#dc2626" }}>
                        {t.type}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </>
          )}

          {/* Goals */}
          {props.goals.length > 0 && (
            <>
              <h2>Goal Progress</h2>
              <table>
                <thead>
                  <tr>
                    <th>Goal</th>
                    <th>Target</th>
                    <th>Saved</th>
                    <th>Progress</th>
                    <th>Status</th>
                  </tr>
                </thead>
                <tbody>
                  {props.goals.map((g, i) => {
                    const pct = g.targetAmount > 0
                      ? Math.min(100, (g.currentAmount / g.targetAmount) * 100)
                      : 0;
                    return (
                      <tr key={i}>
                        <td>{g.title}</td>
                        <td>{formatINR(g.targetAmount)}</td>
                        <td>{formatINR(g.currentAmount)}</td>
                        <td>
                          <div className="progress-bar">
                            <div
                              className="progress-fill ok"
                              style={{ width: `${pct}%` }}
                            />
                          </div>
                          <span style={{ fontSize: 10, color: "#6b7280" }}>{pct.toFixed(0)}%</span>
                        </td>
                        <td>
                          <span className={`badge badge-${g.status}`}>{g.status}</span>
                        </td>
                      </tr>
                    );
                  })}
                </tbody>
              </table>
            </>
          )}
        </div>
      </div>

      <Button variant="outline" onClick={handleDownload} className="flex items-center gap-2 border-slate-600 text-slate-200 hover:bg-slate-700 hover:text-white bg-transparent">
        <Download className="h-4 w-4" />
        Download Report
      </Button>
    </>
  );
}
