-- Expanded Exercise Library
-- Run this after workout-tracker-schema.sql
-- Adds 150+ exercises across all muscle groups

INSERT INTO workout_exercises (user_id, name, muscle_group, equipment, is_custom) VALUES

-- ─── CHEST ────────────────────────────────────────────────────────────────────
  (NULL, 'Bench Press', 'Chest', 'Barbell', FALSE),
  (NULL, 'Incline Bench Press', 'Chest', 'Barbell', FALSE),
  (NULL, 'Decline Bench Press', 'Chest', 'Barbell', FALSE),
  (NULL, 'Close Grip Bench Press', 'Chest', 'Barbell', FALSE),
  (NULL, 'Dumbbell Bench Press', 'Chest', 'Dumbbell', FALSE),
  (NULL, 'Incline Dumbbell Press', 'Chest', 'Dumbbell', FALSE),
  (NULL, 'Decline Dumbbell Press', 'Chest', 'Dumbbell', FALSE),
  (NULL, 'Dumbbell Fly', 'Chest', 'Dumbbell', FALSE),
  (NULL, 'Incline Dumbbell Fly', 'Chest', 'Dumbbell', FALSE),
  (NULL, 'Push Up', 'Chest', 'Bodyweight', FALSE),
  (NULL, 'Wide Grip Push Up', 'Chest', 'Bodyweight', FALSE),
  (NULL, 'Decline Push Up', 'Chest', 'Bodyweight', FALSE),
  (NULL, 'Diamond Push Up', 'Chest', 'Bodyweight', FALSE),
  (NULL, 'Pike Push Up', 'Chest', 'Bodyweight', FALSE),
  (NULL, 'Cable Crossover', 'Chest', 'Cable', FALSE),
  (NULL, 'Low to High Cable Fly', 'Chest', 'Cable', FALSE),
  (NULL, 'High to Low Cable Fly', 'Chest', 'Cable', FALSE),
  (NULL, 'Chest Press Machine', 'Chest', 'Machine', FALSE),
  (NULL, 'Pec Deck Fly', 'Chest', 'Machine', FALSE),
  (NULL, 'Smith Machine Bench Press', 'Chest', 'Machine', FALSE),
  (NULL, 'Chest Dip', 'Chest', 'Bodyweight', FALSE),
  (NULL, 'Svend Press', 'Chest', 'Barbell', FALSE),
  (NULL, 'Landmine Press', 'Chest', 'Barbell', FALSE),

-- ─── BACK ─────────────────────────────────────────────────────────────────────
  (NULL, 'Deadlift', 'Back', 'Barbell', FALSE),
  (NULL, 'Sumo Deadlift', 'Back', 'Barbell', FALSE),
  (NULL, 'Romanian Deadlift', 'Back', 'Barbell', FALSE),
  (NULL, 'Stiff Leg Deadlift', 'Back', 'Barbell', FALSE),
  (NULL, 'Pull Up', 'Back', 'Bodyweight', FALSE),
  (NULL, 'Chin Up', 'Back', 'Bodyweight', FALSE),
  (NULL, 'Wide Grip Pull Up', 'Back', 'Bodyweight', FALSE),
  (NULL, 'Neutral Grip Pull Up', 'Back', 'Bodyweight', FALSE),
  (NULL, 'Barbell Row', 'Back', 'Barbell', FALSE),
  (NULL, 'Pendlay Row', 'Back', 'Barbell', FALSE),
  (NULL, 'T-Bar Row', 'Back', 'Barbell', FALSE),
  (NULL, 'Dumbbell Row', 'Back', 'Dumbbell', FALSE),
  (NULL, 'Chest Supported Row', 'Back', 'Dumbbell', FALSE),
  (NULL, 'Lat Pulldown', 'Back', 'Machine', FALSE),
  (NULL, 'Wide Grip Lat Pulldown', 'Back', 'Machine', FALSE),
  (NULL, 'Reverse Grip Lat Pulldown', 'Back', 'Machine', FALSE),
  (NULL, 'Seated Cable Row', 'Back', 'Cable', FALSE),
  (NULL, 'Wide Grip Cable Row', 'Back', 'Cable', FALSE),
  (NULL, 'Single Arm Cable Row', 'Back', 'Cable', FALSE),
  (NULL, 'Straight Arm Pulldown', 'Back', 'Cable', FALSE),
  (NULL, 'Machine Row', 'Back', 'Machine', FALSE),
  (NULL, 'Meadows Row', 'Back', 'Barbell', FALSE),
  (NULL, 'Inverted Row', 'Back', 'Bodyweight', FALSE),
  (NULL, 'Good Morning', 'Back', 'Barbell', FALSE),
  (NULL, 'Back Extension', 'Back', 'Bodyweight', FALSE),
  (NULL, 'Hyperextension', 'Back', 'Machine', FALSE),
  (NULL, 'Rack Pull', 'Back', 'Barbell', FALSE),
  (NULL, 'Shrug', 'Back', 'Barbell', FALSE),
  (NULL, 'Dumbbell Shrug', 'Back', 'Dumbbell', FALSE),

-- ─── LEGS ─────────────────────────────────────────────────────────────────────
  (NULL, 'Squat', 'Legs', 'Barbell', FALSE),
  (NULL, 'Front Squat', 'Legs', 'Barbell', FALSE),
  (NULL, 'Pause Squat', 'Legs', 'Barbell', FALSE),
  (NULL, 'Box Squat', 'Legs', 'Barbell', FALSE),
  (NULL, 'Goblet Squat', 'Legs', 'Dumbbell', FALSE),
  (NULL, 'Dumbbell Squat', 'Legs', 'Dumbbell', FALSE),
  (NULL, 'Hack Squat', 'Legs', 'Machine', FALSE),
  (NULL, 'Smith Machine Squat', 'Legs', 'Machine', FALSE),
  (NULL, 'Leg Press', 'Legs', 'Machine', FALSE),
  (NULL, 'Bulgarian Split Squat', 'Legs', 'Dumbbell', FALSE),
  (NULL, 'Barbell Split Squat', 'Legs', 'Barbell', FALSE),
  (NULL, 'Walking Lunge', 'Legs', 'Dumbbell', FALSE),
  (NULL, 'Reverse Lunge', 'Legs', 'Dumbbell', FALSE),
  (NULL, 'Barbell Lunge', 'Legs', 'Barbell', FALSE),
  (NULL, 'Step Up', 'Legs', 'Dumbbell', FALSE),
  (NULL, 'Leg Curl', 'Legs', 'Machine', FALSE),
  (NULL, 'Seated Leg Curl', 'Legs', 'Machine', FALSE),
  (NULL, 'Nordic Hamstring Curl', 'Legs', 'Bodyweight', FALSE),
  (NULL, 'Glute Bridge', 'Legs', 'Bodyweight', FALSE),
  (NULL, 'Barbell Hip Thrust', 'Legs', 'Barbell', FALSE),
  (NULL, 'Dumbbell Hip Thrust', 'Legs', 'Dumbbell', FALSE),
  (NULL, 'Cable Kickback', 'Legs', 'Cable', FALSE),
  (NULL, 'Leg Extension', 'Legs', 'Machine', FALSE),
  (NULL, 'Sissy Squat', 'Legs', 'Bodyweight', FALSE),
  (NULL, 'Calf Raise', 'Legs', 'Machine', FALSE),
  (NULL, 'Standing Calf Raise', 'Legs', 'Barbell', FALSE),
  (NULL, 'Seated Calf Raise', 'Legs', 'Machine', FALSE),
  (NULL, 'Donkey Calf Raise', 'Legs', 'Machine', FALSE),
  (NULL, 'Single Leg Calf Raise', 'Legs', 'Bodyweight', FALSE),
  (NULL, 'Sumo Squat', 'Legs', 'Dumbbell', FALSE),
  (NULL, 'Pistol Squat', 'Legs', 'Bodyweight', FALSE),
  (NULL, 'Lying Leg Curl', 'Legs', 'Machine', FALSE),
  (NULL, 'Glute Kickback Machine', 'Legs', 'Machine', FALSE),
  (NULL, 'Hip Abduction Machine', 'Legs', 'Machine', FALSE),
  (NULL, 'Hip Adduction Machine', 'Legs', 'Machine', FALSE),

-- ─── SHOULDERS ────────────────────────────────────────────────────────────────
  (NULL, 'Overhead Press', 'Shoulders', 'Barbell', FALSE),
  (NULL, 'Seated Overhead Press', 'Shoulders', 'Barbell', FALSE),
  (NULL, 'Push Press', 'Shoulders', 'Barbell', FALSE),
  (NULL, 'Arnold Press', 'Shoulders', 'Dumbbell', FALSE),
  (NULL, 'Dumbbell Shoulder Press', 'Shoulders', 'Dumbbell', FALSE),
  (NULL, 'Seated Dumbbell Press', 'Shoulders', 'Dumbbell', FALSE),
  (NULL, 'Smith Machine Shoulder Press', 'Shoulders', 'Machine', FALSE),
  (NULL, 'Machine Shoulder Press', 'Shoulders', 'Machine', FALSE),
  (NULL, 'Dumbbell Lateral Raise', 'Shoulders', 'Dumbbell', FALSE),
  (NULL, 'Cable Lateral Raise', 'Shoulders', 'Cable', FALSE),
  (NULL, 'Machine Lateral Raise', 'Shoulders', 'Machine', FALSE),
  (NULL, 'Front Raise', 'Shoulders', 'Dumbbell', FALSE),
  (NULL, 'Barbell Front Raise', 'Shoulders', 'Barbell', FALSE),
  (NULL, 'Cable Front Raise', 'Shoulders', 'Cable', FALSE),
  (NULL, 'Face Pull', 'Shoulders', 'Cable', FALSE),
  (NULL, 'Reverse Fly', 'Shoulders', 'Dumbbell', FALSE),
  (NULL, 'Bent Over Lateral Raise', 'Shoulders', 'Dumbbell', FALSE),
  (NULL, 'Reverse Pec Deck', 'Shoulders', 'Machine', FALSE),
  (NULL, 'Upright Row', 'Shoulders', 'Barbell', FALSE),
  (NULL, 'Dumbbell Upright Row', 'Shoulders', 'Dumbbell', FALSE),
  (NULL, 'Cable Upright Row', 'Shoulders', 'Cable', FALSE),
  (NULL, 'Landmine Lateral Raise', 'Shoulders', 'Barbell', FALSE),

-- ─── ARMS – BICEPS ────────────────────────────────────────────────────────────
  (NULL, 'Barbell Curl', 'Arms', 'Barbell', FALSE),
  (NULL, 'EZ Bar Curl', 'Arms', 'Barbell', FALSE),
  (NULL, 'Preacher Curl', 'Arms', 'Barbell', FALSE),
  (NULL, 'EZ Bar Preacher Curl', 'Arms', 'Barbell', FALSE),
  (NULL, 'Dumbbell Curl', 'Arms', 'Dumbbell', FALSE),
  (NULL, 'Incline Dumbbell Curl', 'Arms', 'Dumbbell', FALSE),
  (NULL, 'Concentration Curl', 'Arms', 'Dumbbell', FALSE),
  (NULL, 'Spider Curl', 'Arms', 'Dumbbell', FALSE),
  (NULL, 'Hammer Curl', 'Arms', 'Dumbbell', FALSE),
  (NULL, 'Cross Body Hammer Curl', 'Arms', 'Dumbbell', FALSE),
  (NULL, 'Cable Curl', 'Arms', 'Cable', FALSE),
  (NULL, 'High Cable Curl', 'Arms', 'Cable', FALSE),
  (NULL, 'Machine Preacher Curl', 'Arms', 'Machine', FALSE),
  (NULL, 'Reverse Curl', 'Arms', 'Barbell', FALSE),
  (NULL, 'Zottman Curl', 'Arms', 'Dumbbell', FALSE),

-- ─── ARMS – TRICEPS ───────────────────────────────────────────────────────────
  (NULL, 'Tricep Pushdown', 'Arms', 'Cable', FALSE),
  (NULL, 'Rope Pushdown', 'Arms', 'Cable', FALSE),
  (NULL, 'Reverse Grip Pushdown', 'Arms', 'Cable', FALSE),
  (NULL, 'Skull Crusher', 'Arms', 'Barbell', FALSE),
  (NULL, 'EZ Bar Skull Crusher', 'Arms', 'Barbell', FALSE),
  (NULL, 'Dumbbell Skull Crusher', 'Arms', 'Dumbbell', FALSE),
  (NULL, 'Overhead Tricep Extension', 'Arms', 'Dumbbell', FALSE),
  (NULL, 'Barbell Overhead Extension', 'Arms', 'Barbell', FALSE),
  (NULL, 'Cable Overhead Extension', 'Arms', 'Cable', FALSE),
  (NULL, 'Tricep Kickback', 'Arms', 'Dumbbell', FALSE),
  (NULL, 'Tricep Dip', 'Arms', 'Bodyweight', FALSE),
  (NULL, 'Bench Dip', 'Arms', 'Bodyweight', FALSE),
  (NULL, 'Diamond Push Up', 'Arms', 'Bodyweight', FALSE),
  (NULL, 'JM Press', 'Arms', 'Barbell', FALSE),
  (NULL, 'Machine Tricep Extension', 'Arms', 'Machine', FALSE),

-- ─── CORE ─────────────────────────────────────────────────────────────────────
  (NULL, 'Plank', 'Core', 'Bodyweight', FALSE),
  (NULL, 'Side Plank', 'Core', 'Bodyweight', FALSE),
  (NULL, 'Crunch', 'Core', 'Bodyweight', FALSE),
  (NULL, 'Bicycle Crunch', 'Core', 'Bodyweight', FALSE),
  (NULL, 'Reverse Crunch', 'Core', 'Bodyweight', FALSE),
  (NULL, 'Hanging Leg Raise', 'Core', 'Bodyweight', FALSE),
  (NULL, 'Hanging Knee Raise', 'Core', 'Bodyweight', FALSE),
  (NULL, 'Toes to Bar', 'Core', 'Bodyweight', FALSE),
  (NULL, 'Cable Crunch', 'Core', 'Cable', FALSE),
  (NULL, 'Ab Wheel Rollout', 'Core', 'Bodyweight', FALSE),
  (NULL, 'Russian Twist', 'Core', 'Bodyweight', FALSE),
  (NULL, 'Weighted Russian Twist', 'Core', 'Dumbbell', FALSE),
  (NULL, 'V Up', 'Core', 'Bodyweight', FALSE),
  (NULL, 'Hollow Body Hold', 'Core', 'Bodyweight', FALSE),
  (NULL, 'Dead Bug', 'Core', 'Bodyweight', FALSE),
  (NULL, 'Flutter Kicks', 'Core', 'Bodyweight', FALSE),
  (NULL, 'Leg Raise', 'Core', 'Bodyweight', FALSE),
  (NULL, 'Dragon Flag', 'Core', 'Bodyweight', FALSE),
  (NULL, 'Pallof Press', 'Core', 'Cable', FALSE),
  (NULL, 'Woodchopper', 'Core', 'Cable', FALSE),
  (NULL, 'Mountain Climber', 'Core', 'Bodyweight', FALSE),
  (NULL, 'Sit Up', 'Core', 'Bodyweight', FALSE),
  (NULL, 'Decline Sit Up', 'Core', 'Bodyweight', FALSE),
  (NULL, 'Ab Machine Crunch', 'Core', 'Machine', FALSE),

-- ─── CARDIO ───────────────────────────────────────────────────────────────────
  (NULL, 'Running', 'Cardio', 'None', FALSE),
  (NULL, 'Treadmill', 'Cardio', 'Machine', FALSE),
  (NULL, 'Cycling', 'Cardio', 'Machine', FALSE),
  (NULL, 'Stationary Bike', 'Cardio', 'Machine', FALSE),
  (NULL, 'Rowing Machine', 'Cardio', 'Machine', FALSE),
  (NULL, 'Elliptical', 'Cardio', 'Machine', FALSE),
  (NULL, 'Stairmaster', 'Cardio', 'Machine', FALSE),
  (NULL, 'Jump Rope', 'Cardio', 'None', FALSE),
  (NULL, 'Box Jump', 'Cardio', 'Bodyweight', FALSE),
  (NULL, 'Burpee', 'Cardio', 'Bodyweight', FALSE),
  (NULL, 'Jumping Jack', 'Cardio', 'Bodyweight', FALSE),
  (NULL, 'High Knees', 'Cardio', 'Bodyweight', FALSE),
  (NULL, 'Battle Ropes', 'Cardio', 'None', FALSE),
  (NULL, 'Sled Push', 'Cardio', 'None', FALSE),
  (NULL, 'Assault Bike', 'Cardio', 'Machine', FALSE),
  (NULL, 'Swimming', 'Cardio', 'None', FALSE),
  (NULL, 'Sprint', 'Cardio', 'None', FALSE),
  (NULL, 'Incline Treadmill Walk', 'Cardio', 'Machine', FALSE),

-- ─── OTHER / FULL BODY ────────────────────────────────────────────────────────
  (NULL, 'Power Clean', 'Other', 'Barbell', FALSE),
  (NULL, 'Hang Clean', 'Other', 'Barbell', FALSE),
  (NULL, 'Clean and Jerk', 'Other', 'Barbell', FALSE),
  (NULL, 'Snatch', 'Other', 'Barbell', FALSE),
  (NULL, 'Kettlebell Swing', 'Other', 'None', FALSE),
  (NULL, 'Kettlebell Clean', 'Other', 'None', FALSE),
  (NULL, 'Kettlebell Press', 'Other', 'None', FALSE),
  (NULL, 'Turkish Get Up', 'Other', 'None', FALSE),
  (NULL, 'Farmers Walk', 'Other', 'Dumbbell', FALSE),
  (NULL, 'Suitcase Carry', 'Other', 'Dumbbell', FALSE),
  (NULL, 'Bear Hug Carry', 'Other', 'None', FALSE),
  (NULL, 'Thruster', 'Other', 'Barbell', FALSE),
  (NULL, 'Medicine Ball Slam', 'Other', 'None', FALSE),
  (NULL, 'Wall Ball', 'Other', 'None', FALSE),
  (NULL, 'Battle Ropes Waves', 'Other', 'None', FALSE)

ON CONFLICT DO NOTHING;
