-- Comprehensive Exercise Library — matches Hevy exercise database
-- Safe to run multiple times: only inserts exercises that don't already exist

INSERT INTO workout_exercises (user_id, name, muscle_group, equipment, is_custom)
SELECT NULL, t.name, t.muscle_group, t.equipment, FALSE
FROM (VALUES

  -- ─── CHEST ────────────────────────────────────────────────────────────────
  ('Bench Press', 'Chest', 'Barbell'),
  ('Incline Bench Press', 'Chest', 'Barbell'),
  ('Decline Bench Press', 'Chest', 'Barbell'),
  ('Close Grip Bench Press', 'Chest', 'Barbell'),
  ('Wide Grip Bench Press', 'Chest', 'Barbell'),
  ('Paused Bench Press', 'Chest', 'Barbell'),
  ('Floor Press', 'Chest', 'Barbell'),
  ('Dumbbell Bench Press', 'Chest', 'Dumbbell'),
  ('Incline Dumbbell Press', 'Chest', 'Dumbbell'),
  ('Decline Dumbbell Press', 'Chest', 'Dumbbell'),
  ('Dumbbell Fly', 'Chest', 'Dumbbell'),
  ('Incline Dumbbell Fly', 'Chest', 'Dumbbell'),
  ('Decline Dumbbell Fly', 'Chest', 'Dumbbell'),
  ('Dumbbell Pullover', 'Chest', 'Dumbbell'),
  ('Push Up', 'Chest', 'Bodyweight'),
  ('Wide Grip Push Up', 'Chest', 'Bodyweight'),
  ('Decline Push Up', 'Chest', 'Bodyweight'),
  ('Diamond Push Up', 'Chest', 'Bodyweight'),
  ('Pike Push Up', 'Chest', 'Bodyweight'),
  ('Archer Push Up', 'Chest', 'Bodyweight'),
  ('Clap Push Up', 'Chest', 'Bodyweight'),
  ('Chest Dip', 'Chest', 'Bodyweight'),
  ('Ring Push Up', 'Chest', 'Other'),
  ('Cable Crossover', 'Chest', 'Cable'),
  ('Low to High Cable Fly', 'Chest', 'Cable'),
  ('High to Low Cable Fly', 'Chest', 'Cable'),
  ('Cable Fly', 'Chest', 'Cable'),
  ('Standing Cable Fly', 'Chest', 'Cable'),
  ('Pec Dec Fly', 'Chest', 'Machine'),
  ('Pec Deck Fly', 'Chest', 'Machine'),
  ('Seated Pec Dec', 'Chest', 'Machine'),
  ('Machine Fly', 'Chest', 'Machine'),
  ('Chest Press Machine', 'Chest', 'Machine'),
  ('Incline Chest Press Machine', 'Chest', 'Machine'),
  ('Decline Chest Press Machine', 'Chest', 'Machine'),
  ('Chest Fly Machine', 'Chest', 'Machine'),
  ('Smith Machine Bench Press', 'Chest', 'Machine'),
  ('Smith Machine Incline Press', 'Chest', 'Machine'),
  ('Svend Press', 'Chest', 'Plate'),
  ('Landmine Press', 'Chest', 'Barbell'),
  ('Landmine Fly', 'Chest', 'Barbell'),
  ('Banded Push Up', 'Chest', 'Resistance Band'),
  ('Push Up (Resistance Band)', 'Chest', 'Resistance Band'),

  -- ─── BACK ─────────────────────────────────────────────────────────────────
  ('Deadlift', 'Back', 'Barbell'),
  ('Romanian Deadlift', 'Back', 'Barbell'),
  ('Stiff Leg Deadlift', 'Back', 'Barbell'),
  ('Deficit Deadlift', 'Back', 'Barbell'),
  ('Sumo Deadlift', 'Back', 'Barbell'),
  ('Barbell Row', 'Back', 'Barbell'),
  ('Pendlay Row', 'Back', 'Barbell'),
  ('Yates Row', 'Back', 'Barbell'),
  ('T-Bar Row', 'Back', 'Barbell'),
  ('Meadows Row', 'Back', 'Barbell'),
  ('Landmine Row', 'Back', 'Barbell'),
  ('Dumbbell Row', 'Back', 'Dumbbell'),
  ('Single Arm Dumbbell Row', 'Back', 'Dumbbell'),
  ('Chest Supported Row', 'Back', 'Dumbbell'),
  ('Incline Dumbbell Row', 'Back', 'Dumbbell'),
  ('Dumbbell Deadlift', 'Back', 'Dumbbell'),
  ('Dumbbell Romanian Deadlift', 'Back', 'Dumbbell'),
  ('Dumbbell Pullover', 'Back', 'Dumbbell'),
  ('Pull Up', 'Back', 'Bodyweight'),
  ('Chin Up', 'Back', 'Bodyweight'),
  ('Wide Grip Pull Up', 'Back', 'Bodyweight'),
  ('Close Grip Pull Up', 'Back', 'Bodyweight'),
  ('Neutral Grip Pull Up', 'Back', 'Bodyweight'),
  ('Weighted Pull Up', 'Back', 'Bodyweight'),
  ('Band Assisted Pull Up', 'Back', 'Resistance Band'),
  ('Inverted Row', 'Back', 'Bodyweight'),
  ('Ring Row', 'Back', 'Other'),
  ('Lat Pulldown', 'Back', 'Cable'),
  ('Wide Grip Lat Pulldown', 'Back', 'Cable'),
  ('Close Grip Lat Pulldown', 'Back', 'Cable'),
  ('Neutral Grip Lat Pulldown', 'Back', 'Cable'),
  ('Reverse Grip Lat Pulldown', 'Back', 'Cable'),
  ('Single Arm Lat Pulldown', 'Back', 'Cable'),
  ('Straight Arm Lat Pulldown', 'Back', 'Cable'),
  ('Cable Row', 'Back', 'Cable'),
  ('Seated Cable Row', 'Back', 'Cable'),
  ('Wide Grip Cable Row', 'Back', 'Cable'),
  ('Single Arm Cable Row', 'Back', 'Cable'),
  ('Face Pull', 'Back', 'Cable'),
  ('Cable Pullover', 'Back', 'Cable'),
  ('Machine Row', 'Back', 'Machine'),
  ('Chest Supported Machine Row', 'Back', 'Machine'),
  ('Machine Lat Pulldown', 'Back', 'Machine'),
  ('Hammer Strength Row', 'Back', 'Machine'),
  ('Seated Machine Row', 'Back', 'Machine'),
  ('Back Extension', 'Back', 'Bodyweight'),
  ('Hyperextension', 'Back', 'Bodyweight'),
  ('Good Morning', 'Back', 'Barbell'),
  ('Superman', 'Back', 'Bodyweight'),
  ('Rack Pull', 'Back', 'Barbell'),
  ('Trap Bar Deadlift', 'Back', 'Other'),
  ('Kettlebell Deadlift', 'Back', 'Kettlebell'),
  ('Kettlebell Row', 'Back', 'Kettlebell'),
  ('Shrug', 'Back', 'Barbell'),
  ('Dumbbell Shrug', 'Back', 'Dumbbell'),
  ('Cable Shrug', 'Back', 'Cable'),
  ('Machine Shrug', 'Back', 'Machine'),

  -- ─── SHOULDERS ────────────────────────────────────────────────────────────
  ('Overhead Press', 'Shoulders', 'Barbell'),
  ('Military Press', 'Shoulders', 'Barbell'),
  ('Push Press', 'Shoulders', 'Barbell'),
  ('Behind the Neck Press', 'Shoulders', 'Barbell'),
  ('Seated Overhead Press', 'Shoulders', 'Barbell'),
  ('Z Press', 'Shoulders', 'Barbell'),
  ('Dumbbell Shoulder Press', 'Shoulders', 'Dumbbell'),
  ('Seated Dumbbell Press', 'Shoulders', 'Dumbbell'),
  ('Arnold Press', 'Shoulders', 'Dumbbell'),
  ('Single Arm Dumbbell Press', 'Shoulders', 'Dumbbell'),
  ('Lateral Raise', 'Shoulders', 'Dumbbell'),
  ('Cable Lateral Raise', 'Shoulders', 'Cable'),
  ('Machine Lateral Raise', 'Shoulders', 'Machine'),
  ('Seated Lateral Raise', 'Shoulders', 'Dumbbell'),
  ('Leaning Lateral Raise', 'Shoulders', 'Dumbbell'),
  ('Front Raise', 'Shoulders', 'Dumbbell'),
  ('Barbell Front Raise', 'Shoulders', 'Barbell'),
  ('Cable Front Raise', 'Shoulders', 'Cable'),
  ('Plate Front Raise', 'Shoulders', 'Plate'),
  ('Reverse Fly', 'Shoulders', 'Dumbbell'),
  ('Reverse Pec Dec Fly', 'Shoulders', 'Machine'),
  ('Reverse Pec Deck', 'Shoulders', 'Machine'),
  ('Bent Over Reverse Fly', 'Shoulders', 'Dumbbell'),
  ('Cable Reverse Fly', 'Shoulders', 'Cable'),
  ('Machine Reverse Fly', 'Shoulders', 'Machine'),
  ('Upright Row', 'Shoulders', 'Barbell'),
  ('Dumbbell Upright Row', 'Shoulders', 'Dumbbell'),
  ('Cable Upright Row', 'Shoulders', 'Cable'),
  ('Face Pull', 'Shoulders', 'Cable'),
  ('Band Pull Apart', 'Shoulders', 'Resistance Band'),
  ('YTW Raise', 'Shoulders', 'Dumbbell'),
  ('Y Raise', 'Shoulders', 'Dumbbell'),
  ('T Raise', 'Shoulders', 'Dumbbell'),
  ('W Raise', 'Shoulders', 'Dumbbell'),
  ('Machine Shoulder Press', 'Shoulders', 'Machine'),
  ('Smith Machine Shoulder Press', 'Shoulders', 'Machine'),
  ('Landmine Lateral Raise', 'Shoulders', 'Barbell'),
  ('Landmine Press (Shoulder)', 'Shoulders', 'Barbell'),
  ('Cable Shoulder Press', 'Shoulders', 'Cable'),
  ('Handstand Push Up', 'Shoulders', 'Bodyweight'),
  ('Pike Push Up', 'Shoulders', 'Bodyweight'),

  -- ─── ARMS (Biceps) ────────────────────────────────────────────────────────
  ('Barbell Curl', 'Arms', 'Barbell'),
  ('EZ Bar Curl', 'Arms', 'Barbell'),
  ('Wide Grip Barbell Curl', 'Arms', 'Barbell'),
  ('Reverse Barbell Curl', 'Arms', 'Barbell'),
  ('Preacher Curl', 'Arms', 'Barbell'),
  ('EZ Bar Preacher Curl', 'Arms', 'Barbell'),
  ('Dumbbell Curl', 'Arms', 'Dumbbell'),
  ('Alternating Dumbbell Curl', 'Arms', 'Dumbbell'),
  ('Hammer Curl', 'Arms', 'Dumbbell'),
  ('Alternating Hammer Curl', 'Arms', 'Dumbbell'),
  ('Incline Dumbbell Curl', 'Arms', 'Dumbbell'),
  ('Concentration Curl', 'Arms', 'Dumbbell'),
  ('Zottman Curl', 'Arms', 'Dumbbell'),
  ('Reverse Curl', 'Arms', 'Dumbbell'),
  ('Spider Curl', 'Arms', 'Dumbbell'),
  ('Cross Body Hammer Curl', 'Arms', 'Dumbbell'),
  ('Cable Curl', 'Arms', 'Cable'),
  ('Cable Hammer Curl', 'Arms', 'Cable'),
  ('Low Cable Curl', 'Arms', 'Cable'),
  ('High Cable Curl', 'Arms', 'Cable'),
  ('Single Arm Cable Curl', 'Arms', 'Cable'),
  ('Rope Hammer Curl', 'Arms', 'Cable'),
  ('Preacher Curl Machine', 'Arms', 'Machine'),
  ('Machine Curl', 'Arms', 'Machine'),
  ('Resistance Band Curl', 'Arms', 'Resistance Band'),
  ('Scott Curl', 'Arms', 'Barbell'),
  ('21s Curl', 'Arms', 'Barbell'),
  ('Bayesian Curl', 'Arms', 'Cable'),

  -- ─── ARMS (Triceps) ───────────────────────────────────────────────────────
  ('Tricep Pushdown', 'Arms', 'Cable'),
  ('Rope Pushdown', 'Arms', 'Cable'),
  ('Bar Pushdown', 'Arms', 'Cable'),
  ('Reverse Grip Pushdown', 'Arms', 'Cable'),
  ('Single Arm Pushdown', 'Arms', 'Cable'),
  ('Overhead Cable Tricep Extension', 'Arms', 'Cable'),
  ('Single Arm Cable Overhead Extension', 'Arms', 'Cable'),
  ('Tricep Extension', 'Arms', 'Dumbbell'),
  ('Overhead Tricep Extension', 'Arms', 'Dumbbell'),
  ('Single Arm Overhead Tricep Extension', 'Arms', 'Dumbbell'),
  ('Lying Tricep Extension', 'Arms', 'Dumbbell'),
  ('Skull Crushers', 'Arms', 'Barbell'),
  ('EZ Bar Skull Crusher', 'Arms', 'Barbell'),
  ('Close Grip Bench Press', 'Arms', 'Barbell'),
  ('Barbell Overhead Tricep Extension', 'Arms', 'Barbell'),
  ('Lying Barbell Tricep Extension', 'Arms', 'Barbell'),
  ('Tricep Dip', 'Arms', 'Bodyweight'),
  ('Bench Dip', 'Arms', 'Bodyweight'),
  ('Weighted Tricep Dip', 'Arms', 'Bodyweight'),
  ('Diamond Push Up', 'Arms', 'Bodyweight'),
  ('Machine Tricep Extension', 'Arms', 'Machine'),
  ('Tricep Kickback', 'Arms', 'Dumbbell'),
  ('Cable Tricep Kickback', 'Arms', 'Cable'),
  ('JM Press', 'Arms', 'Barbell'),
  ('Tate Press', 'Arms', 'Dumbbell'),
  ('Band Tricep Pushdown', 'Arms', 'Resistance Band'),

  -- ─── ARMS (Forearms) ──────────────────────────────────────────────────────
  ('Wrist Curl', 'Arms', 'Barbell'),
  ('Reverse Wrist Curl', 'Arms', 'Barbell'),
  ('Dumbbell Wrist Curl', 'Arms', 'Dumbbell'),
  ('Reverse Dumbbell Wrist Curl', 'Arms', 'Dumbbell'),
  ('Behind the Back Wrist Curl', 'Arms', 'Barbell'),
  ('Farmers Walk', 'Arms', 'Dumbbell'),
  ('Plate Pinch', 'Arms', 'Plate'),
  ('Towel Pull Up', 'Arms', 'Bodyweight'),
  ('Dead Hang', 'Arms', 'Bodyweight'),
  ('Reverse Curl (Forearm)', 'Arms', 'Barbell'),

  -- ─── LEGS (Quads) ─────────────────────────────────────────────────────────
  ('Squat', 'Legs', 'Barbell'),
  ('Back Squat', 'Legs', 'Barbell'),
  ('Front Squat', 'Legs', 'Barbell'),
  ('Overhead Squat', 'Legs', 'Barbell'),
  ('Paused Squat', 'Legs', 'Barbell'),
  ('Low Bar Squat', 'Legs', 'Barbell'),
  ('High Bar Squat', 'Legs', 'Barbell'),
  ('Box Squat', 'Legs', 'Barbell'),
  ('Dumbbell Squat', 'Legs', 'Dumbbell'),
  ('Goblet Squat', 'Legs', 'Dumbbell'),
  ('Goblet Squat (Kettlebell)', 'Legs', 'Kettlebell'),
  ('Smith Machine Squat', 'Legs', 'Machine'),
  ('Hack Squat', 'Legs', 'Machine'),
  ('Leg Press', 'Legs', 'Machine'),
  ('Single Leg Press', 'Legs', 'Machine'),
  ('Leg Extension', 'Legs', 'Machine'),
  ('Single Leg Extension', 'Legs', 'Machine'),
  ('Lunge', 'Legs', 'Barbell'),
  ('Dumbbell Lunge', 'Legs', 'Dumbbell'),
  ('Walking Lunge', 'Legs', 'Dumbbell'),
  ('Reverse Lunge', 'Legs', 'Dumbbell'),
  ('Bulgarian Split Squat', 'Legs', 'Dumbbell'),
  ('Barbell Bulgarian Split Squat', 'Legs', 'Barbell'),
  ('Step Up', 'Legs', 'Dumbbell'),
  ('Barbell Step Up', 'Legs', 'Barbell'),
  ('Sissy Squat', 'Legs', 'Bodyweight'),
  ('Pistol Squat', 'Legs', 'Bodyweight'),
  ('Air Squat', 'Legs', 'Bodyweight'),
  ('Jump Squat', 'Legs', 'Bodyweight'),
  ('Landmine Squat', 'Legs', 'Barbell'),
  ('Zercher Squat', 'Legs', 'Barbell'),
  ('Safety Bar Squat', 'Legs', 'Barbell'),
  ('Wall Sit', 'Legs', 'Bodyweight'),

  -- ─── LEGS (Hamstrings) ────────────────────────────────────────────────────
  ('Romanian Deadlift', 'Legs', 'Barbell'),
  ('Dumbbell Romanian Deadlift', 'Legs', 'Dumbbell'),
  ('Leg Curl', 'Legs', 'Machine'),
  ('Lying Leg Curl', 'Legs', 'Machine'),
  ('Seated Leg Curl', 'Legs', 'Machine'),
  ('Standing Leg Curl', 'Legs', 'Machine'),
  ('Single Leg Curl', 'Legs', 'Machine'),
  ('Nordic Hamstring Curl', 'Legs', 'Bodyweight'),
  ('Good Morning', 'Legs', 'Barbell'),
  ('Stiff Leg Deadlift', 'Legs', 'Barbell'),
  ('Single Leg Romanian Deadlift', 'Legs', 'Dumbbell'),
  ('Swiss Ball Leg Curl', 'Legs', 'Other'),
  ('Glute Ham Raise', 'Legs', 'Bodyweight'),

  -- ─── LEGS (Glutes) ────────────────────────────────────────────────────────
  ('Hip Thrust', 'Legs', 'Barbell'),
  ('Dumbbell Hip Thrust', 'Legs', 'Dumbbell'),
  ('Machine Hip Thrust', 'Legs', 'Machine'),
  ('Glute Bridge', 'Legs', 'Bodyweight'),
  ('Barbell Glute Bridge', 'Legs', 'Barbell'),
  ('Single Leg Hip Thrust', 'Legs', 'Bodyweight'),
  ('Cable Kickback', 'Legs', 'Cable'),
  ('Donkey Kick', 'Legs', 'Bodyweight'),
  ('Fire Hydrant', 'Legs', 'Bodyweight'),
  ('Hip Abduction Machine', 'Legs', 'Machine'),
  ('Hip Adduction Machine', 'Legs', 'Machine'),
  ('Sumo Squat', 'Legs', 'Dumbbell'),
  ('Cable Pull Through', 'Legs', 'Cable'),
  ('Kettlebell Swing', 'Legs', 'Kettlebell'),
  ('Frog Pump', 'Legs', 'Bodyweight'),

  -- ─── LEGS (Calves) ────────────────────────────────────────────────────────
  ('Standing Calf Raise', 'Legs', 'Machine'),
  ('Seated Calf Raise', 'Legs', 'Machine'),
  ('Leg Press Calf Raise', 'Legs', 'Machine'),
  ('Dumbbell Calf Raise', 'Legs', 'Dumbbell'),
  ('Barbell Calf Raise', 'Legs', 'Barbell'),
  ('Single Leg Calf Raise', 'Legs', 'Bodyweight'),
  ('Donkey Calf Raise', 'Legs', 'Machine'),
  ('Tibialis Raise', 'Legs', 'Bodyweight'),

  -- ─── CORE ─────────────────────────────────────────────────────────────────
  ('Crunch', 'Core', 'Bodyweight'),
  ('Sit Up', 'Core', 'Bodyweight'),
  ('Decline Sit Up', 'Core', 'Bodyweight'),
  ('Weighted Sit Up', 'Core', 'Plate'),
  ('Plank', 'Core', 'Bodyweight'),
  ('Side Plank', 'Core', 'Bodyweight'),
  ('Long Lever Plank', 'Core', 'Bodyweight'),
  ('RKC Plank', 'Core', 'Bodyweight'),
  ('Dead Bug', 'Core', 'Bodyweight'),
  ('Bird Dog', 'Core', 'Bodyweight'),
  ('Leg Raise', 'Core', 'Bodyweight'),
  ('Hanging Leg Raise', 'Core', 'Bodyweight'),
  ('Hanging Knee Raise', 'Core', 'Bodyweight'),
  ('Toes to Bar', 'Core', 'Bodyweight'),
  ('Knee to Elbow', 'Core', 'Bodyweight'),
  ('L-Sit', 'Core', 'Bodyweight'),
  ('Ab Wheel Rollout', 'Core', 'Other'),
  ('Cable Crunch', 'Core', 'Cable'),
  ('Kneeling Cable Crunch', 'Core', 'Cable'),
  ('Machine Crunch', 'Core', 'Machine'),
  ('Pallof Press', 'Core', 'Cable'),
  ('Oblique Crunch', 'Core', 'Bodyweight'),
  ('Russian Twist', 'Core', 'Bodyweight'),
  ('Weighted Russian Twist', 'Core', 'Plate'),
  ('Bicycle Crunch', 'Core', 'Bodyweight'),
  ('Mountain Climber', 'Core', 'Bodyweight'),
  ('V-Up', 'Core', 'Bodyweight'),
  ('Hollow Body Hold', 'Core', 'Bodyweight'),
  ('Hollow Body Rock', 'Core', 'Bodyweight'),
  ('Dragon Flag', 'Core', 'Bodyweight'),
  ('Turkish Get Up', 'Core', 'Kettlebell'),
  ('Windmill', 'Core', 'Kettlebell'),
  ('Landmine Rotation', 'Core', 'Barbell'),
  ('Woodchopper', 'Core', 'Cable'),
  ('Medicine Ball Slam', 'Core', 'Other'),
  ('Farmer Carry', 'Core', 'Dumbbell'),
  ('Suitcase Carry', 'Core', 'Dumbbell'),
  ('Overhead Carry', 'Core', 'Dumbbell'),
  ('Copenhagen Plank', 'Core', 'Bodyweight'),
  ('Reverse Crunch', 'Core', 'Bodyweight'),
  ('Flutter Kick', 'Core', 'Bodyweight'),
  ('Scissor Kick', 'Core', 'Bodyweight'),

  -- ─── CARDIO ───────────────────────────────────────────────────────────────
  ('Running', 'Cardio', 'Cardio'),
  ('Treadmill Running', 'Cardio', 'Cardio'),
  ('Treadmill Walking', 'Cardio', 'Cardio'),
  ('Incline Treadmill Walk', 'Cardio', 'Cardio'),
  ('Cycling', 'Cardio', 'Cardio'),
  ('Stationary Bike', 'Cardio', 'Cardio'),
  ('Rowing Machine', 'Cardio', 'Cardio'),
  ('Rowing (Outdoor)', 'Cardio', 'Cardio'),
  ('Elliptical', 'Cardio', 'Cardio'),
  ('Stair Climber', 'Cardio', 'Cardio'),
  ('Jump Rope', 'Cardio', 'Other'),
  ('Box Jump', 'Cardio', 'Bodyweight'),
  ('Burpee', 'Cardio', 'Bodyweight'),
  ('Jumping Jack', 'Cardio', 'Bodyweight'),
  ('High Knees', 'Cardio', 'Bodyweight'),
  ('Assault Bike', 'Cardio', 'Cardio'),
  ('Ski Erg', 'Cardio', 'Cardio'),
  ('Swimming', 'Cardio', 'Cardio'),
  ('Sled Push', 'Cardio', 'Other'),
  ('Sled Pull', 'Cardio', 'Other'),
  ('Battle Ropes', 'Cardio', 'Other'),
  ('Sprints', 'Cardio', 'Bodyweight'),

  -- ─── OLYMPIC / POWER ──────────────────────────────────────────────────────
  ('Clean', 'Other', 'Barbell'),
  ('Power Clean', 'Other', 'Barbell'),
  ('Hang Clean', 'Other', 'Barbell'),
  ('Squat Clean', 'Other', 'Barbell'),
  ('Clean and Jerk', 'Other', 'Barbell'),
  ('Snatch', 'Other', 'Barbell'),
  ('Power Snatch', 'Other', 'Barbell'),
  ('Hang Snatch', 'Other', 'Barbell'),
  ('Jerk', 'Other', 'Barbell'),
  ('Push Jerk', 'Other', 'Barbell'),
  ('Split Jerk', 'Other', 'Barbell'),
  ('Muscle Up', 'Other', 'Bodyweight'),
  ('Ring Muscle Up', 'Other', 'Other'),
  ('Kettlebell Clean', 'Other', 'Kettlebell'),
  ('Kettlebell Snatch', 'Other', 'Kettlebell'),
  ('Kettlebell Press', 'Shoulders', 'Kettlebell'),
  ('Kettlebell Push Press', 'Shoulders', 'Kettlebell'),
  ('Kettlebell Windmill', 'Core', 'Kettlebell'),
  ('Kettlebell Goblet Squat', 'Legs', 'Kettlebell'),
  ('Kettlebell Hip Thrust', 'Legs', 'Kettlebell'),
  ('Kettlebell Romanian Deadlift', 'Back', 'Kettlebell'),
  ('Kettlebell Swing', 'Other', 'Kettlebell'),
  ('Kettlebell Turkish Get Up', 'Other', 'Kettlebell'),

  -- ─── OTHER / FULL BODY ────────────────────────────────────────────────────
  ('Thruster', 'Other', 'Barbell'),
  ('Dumbbell Thruster', 'Other', 'Dumbbell'),
  ('Devil Press', 'Other', 'Dumbbell'),
  ('Man Maker', 'Other', 'Dumbbell'),
  ('Bear Complex', 'Other', 'Barbell'),
  ('Sandbag Carry', 'Other', 'Other'),
  ('Atlas Stone', 'Other', 'Other'),
  ('Tire Flip', 'Other', 'Other'),
  ('Rope Climb', 'Other', 'Bodyweight'),
  ('Sledgehammer Slam', 'Other', 'Other'),
  ('Band Pull Apart', 'Other', 'Resistance Band'),
  ('Pull Apart (Resistance Band)', 'Other', 'Resistance Band'),
  ('Hip Circle Walk', 'Legs', 'Resistance Band'),
  ('Clamshell', 'Legs', 'Resistance Band'),
  ('Banded Squat Walk', 'Legs', 'Resistance Band'),
  ('Banded Hip Thrust', 'Legs', 'Resistance Band'),
  ('Banded Deadlift', 'Back', 'Resistance Band'),
  ('Face Pull (Resistance Band)', 'Shoulders', 'Resistance Band'),
  ('Banded Row', 'Back', 'Resistance Band'),
  ('Chest Press (Resistance Band)', 'Chest', 'Resistance Band'),
  ('Overhead Press (Resistance Band)', 'Shoulders', 'Resistance Band'),
  ('Tricep Pushdown (Resistance Band)', 'Arms', 'Resistance Band'),
  ('Bicep Curl (Resistance Band)', 'Arms', 'Resistance Band'),
  ('Lateral Walk (Resistance Band)', 'Legs', 'Resistance Band')

) AS t(name, muscle_group, equipment)
WHERE NOT EXISTS (
  SELECT 1 FROM workout_exercises e
  WHERE e.name = t.name AND e.user_id IS NULL
);
