// Static mapping of our exercise names → free-exercise-db IDs
// Images: https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/{id}/0.jpg

const BASE = "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises";

const EXERCISE_IMAGE_MAP: Record<string, string> = {
  // ─── CHEST ───────────────────────────────────────────────────────────────────
  "Bench Press":                  `${BASE}/Barbell_Bench_Press_-_Medium_Grip/0.jpg`,
  "Incline Bench Press":          `${BASE}/Barbell_Incline_Bench_Press_-_Medium_Grip/0.jpg`,
  "Decline Bench Press":          `${BASE}/Decline_Barbell_Bench_Press/0.jpg`,
  "Close Grip Bench Press":       `${BASE}/Close-Grip_Barbell_Bench_Press/0.jpg`,
  "Dumbbell Bench Press":         `${BASE}/Dumbbell_Bench_Press/0.jpg`,
  "Incline Dumbbell Press":       `${BASE}/Incline_Dumbbell_Press/0.jpg`,
  "Decline Dumbbell Press":       `${BASE}/Decline_Dumbbell_Bench_Press/0.jpg`,
  "Dumbbell Fly":                 `${BASE}/Dumbbell_Flyes/0.jpg`,
  "Incline Dumbbell Fly":         `${BASE}/Incline_Dumbbell_Flyes/0.jpg`,
  "Push Up":                      `${BASE}/Push-Up/0.jpg`,
  "Wide Grip Push Up":            `${BASE}/Wide-Grip_Barbell_Bench_Press/0.jpg`,
  "Decline Push Up":              `${BASE}/Decline_Push-Up/0.jpg`,
  "Diamond Push Up":              `${BASE}/Close-Grip_Push-Up/0.jpg`,
  "Pike Push Up":                 `${BASE}/Pike_Push-up/0.jpg`,
  "Cable Crossover":              `${BASE}/Cable_Crossover/0.jpg`,
  "Low to High Cable Fly":        `${BASE}/Cable_Crossover/0.jpg`,
  "High to Low Cable Fly":        `${BASE}/Cable_Crossover/1.jpg`,
  "Chest Press Machine":          `${BASE}/Lever_Incline_Chest_Press/0.jpg`,
  "Pec Deck Fly":                 `${BASE}/Pec_Deck_Fly/0.jpg`,
  "Smith Machine Bench Press":    `${BASE}/Smith_Machine_Bench_Press/0.jpg`,
  "Chest Dip":                    `${BASE}/Chest_Dip/0.jpg`,
  "Svend Press":                  `${BASE}/Svend_Press/0.jpg`,
  "Landmine Press":               `${BASE}/Landmine_twist/0.jpg`,

  // ─── BACK ────────────────────────────────────────────────────────────────────
  "Deadlift":                     `${BASE}/Barbell_Deadlift/0.jpg`,
  "Sumo Deadlift":                `${BASE}/Sumo_Deadlift/0.jpg`,
  "Romanian Deadlift":            `${BASE}/Romanian_Deadlift/0.jpg`,
  "Stiff Leg Deadlift":           `${BASE}/Stiff-Legged_Barbell_Deadlift/0.jpg`,
  "Pull Up":                      `${BASE}/Pull-Up/0.jpg`,
  "Chin Up":                      `${BASE}/Chin-Up/0.jpg`,
  "Wide Grip Pull Up":            `${BASE}/Wide-Grip_Lat_Pulldown/0.jpg`,
  "Neutral Grip Pull Up":         `${BASE}/Pull-Up/0.jpg`,
  "Barbell Row":                  `${BASE}/Bent_Over_Barbell_Row/0.jpg`,
  "Pendlay Row":                  `${BASE}/Bent_Over_Barbell_Row/1.jpg`,
  "T-Bar Row":                    `${BASE}/T-Bar_Row_with_Handle/0.jpg`,
  "Dumbbell Row":                 `${BASE}/One-Arm_Dumbbell_Row/0.jpg`,
  "Chest Supported Row":          `${BASE}/Incline_Dumbbell_Rows/0.jpg`,
  "Lat Pulldown":                 `${BASE}/Lat_Pulldown/0.jpg`,
  "Wide Grip Lat Pulldown":       `${BASE}/Wide-Grip_Lat_Pulldown/0.jpg`,
  "Reverse Grip Lat Pulldown":    `${BASE}/Reverse_Grip_Bent-Over_Rows/0.jpg`,
  "Seated Cable Row":             `${BASE}/Seated_Cable_Rows/0.jpg`,
  "Wide Grip Cable Row":          `${BASE}/Seated_Cable_Rows/1.jpg`,
  "Single Arm Cable Row":         `${BASE}/Cable_Seated_Row/0.jpg`,
  "Straight Arm Pulldown":        `${BASE}/Straight-Arm_Pulldown/0.jpg`,
  "Machine Row":                  `${BASE}/Lever_Seated_Row/0.jpg`,
  "Meadows Row":                  `${BASE}/Bent_Over_One-Arm_Long_Bar_Row/0.jpg`,
  "Inverted Row":                 `${BASE}/Inverted_Row_with_Straddle/0.jpg`,
  "Good Morning":                 `${BASE}/Good_Morning/0.jpg`,
  "Back Extension":               `${BASE}/Back_Extension/0.jpg`,
  "Hyperextension":               `${BASE}/Hyperextensions_With_No_Hyperextension_Bench/0.jpg`,
  "Rack Pull":                    `${BASE}/Rack_Pull/0.jpg`,
  "Shrug":                        `${BASE}/Barbell_Shrug/0.jpg`,
  "Dumbbell Shrug":               `${BASE}/Dumbbell_Shrug/0.jpg`,

  // ─── LEGS ────────────────────────────────────────────────────────────────────
  "Squat":                        `${BASE}/Barbell_Squat/0.jpg`,
  "Front Squat":                  `${BASE}/Barbell_Front_Squat/0.jpg`,
  "Pause Squat":                  `${BASE}/Barbell_Squat/1.jpg`,
  "Box Squat":                    `${BASE}/Barbell_Squat_To_A_Bench/0.jpg`,
  "Goblet Squat":                 `${BASE}/Dumbbell_Goblet_Squat/0.jpg`,
  "Dumbbell Squat":               `${BASE}/Dumbbell_Squat/0.jpg`,
  "Hack Squat":                   `${BASE}/Barbell_Hack_Squat/0.jpg`,
  "Smith Machine Squat":          `${BASE}/Smith_Machine_Squat/0.jpg`,
  "Leg Press":                    `${BASE}/Leg_Press/0.jpg`,
  "Bulgarian Split Squat":        `${BASE}/Barbell_Bulgarian_Split_Squat/0.jpg`,
  "Barbell Split Squat":          `${BASE}/Barbell_Bulgarian_Split_Squat/1.jpg`,
  "Walking Lunge":                `${BASE}/Barbell_Walking_Lunge/0.jpg`,
  "Reverse Lunge":                `${BASE}/Dumbbell_Rear_Lunge/0.jpg`,
  "Barbell Lunge":                `${BASE}/Barbell_Lunge/0.jpg`,
  "Step Up":                      `${BASE}/Barbell_Step_Ups/0.jpg`,
  "Leg Curl":                     `${BASE}/Leg_Curl/0.jpg`,
  "Seated Leg Curl":              `${BASE}/Seated_Leg_Curl/0.jpg`,
  "Nordic Hamstring Curl":        `${BASE}/Natural_Glute_Ham_Raise/0.jpg`,
  "Glute Bridge":                 `${BASE}/Barbell_Glute_Bridge/0.jpg`,
  "Barbell Hip Thrust":           `${BASE}/Barbell_Hip_Thrust/0.jpg`,
  "Dumbbell Hip Thrust":          `${BASE}/Dumbbell_Hip_Thrust/0.jpg`,
  "Cable Kickback":               `${BASE}/Cable_Hip_Adduction/0.jpg`,
  "Leg Extension":                `${BASE}/Leg_Extensions/0.jpg`,
  "Sissy Squat":                  `${BASE}/Sissy_Squat/0.jpg`,
  "Calf Raise":                   `${BASE}/Standing_Calf_Raises/0.jpg`,
  "Standing Calf Raise":          `${BASE}/Standing_Calf_Raises/0.jpg`,
  "Seated Calf Raise":            `${BASE}/Seated_Calf_Raise/0.jpg`,
  "Donkey Calf Raise":            `${BASE}/Donkey_Calf_Raises/0.jpg`,
  "Single Leg Calf Raise":        `${BASE}/Standing_Calf_Raises/1.jpg`,
  "Sumo Squat":                   `${BASE}/Dumbbell_Sumo_Squat/0.jpg`,
  "Pistol Squat":                 `${BASE}/Pistol_Squat/0.jpg`,
  "Lying Leg Curl":               `${BASE}/Lying_Leg_Curls/0.jpg`,
  "Glute Kickback Machine":       `${BASE}/Lever_Hip_Extension/0.jpg`,
  "Hip Abduction Machine":        `${BASE}/Lever_Seated_Hip_Abduction/0.jpg`,
  "Hip Adduction Machine":        `${BASE}/Lever_Seated_Hip_Adduction/0.jpg`,

  // ─── SHOULDERS ───────────────────────────────────────────────────────────────
  "Overhead Press":               `${BASE}/Barbell_Shoulder_Press/0.jpg`,
  "Seated Overhead Press":        `${BASE}/Barbell_Seated_Behind_Neck_Press/0.jpg`,
  "Push Press":                   `${BASE}/Push_Press/0.jpg`,
  "Arnold Press":                 `${BASE}/Arnold_Dumbbell_Press/0.jpg`,
  "Dumbbell Shoulder Press":      `${BASE}/Dumbbell_Shoulder_Press/0.jpg`,
  "Seated Dumbbell Press":        `${BASE}/Seated_Dumbbell_Palms_In_Alternate_Front_Raise/0.jpg`,
  "Smith Machine Shoulder Press": `${BASE}/Smith_Machine_Overhead_Press/0.jpg`,
  "Machine Shoulder Press":       `${BASE}/Lever_Overhead_Press/0.jpg`,
  "Dumbbell Lateral Raise":       `${BASE}/Side_Lateral_Raise/0.jpg`,
  "Cable Lateral Raise":          `${BASE}/Bent_Over_Low-Pulley_Side_Lateral/0.jpg`,
  "Machine Lateral Raise":        `${BASE}/Lever_Lateral_Raise/0.jpg`,
  "Front Raise":                  `${BASE}/Dumbbell_Front_Raise/0.jpg`,
  "Barbell Front Raise":          `${BASE}/Barbell_Raise/0.jpg`,
  "Cable Front Raise":            `${BASE}/Cable_Front_Raise/0.jpg`,
  "Face Pull":                    `${BASE}/Face_Pull/0.jpg`,
  "Reverse Fly":                  `${BASE}/Reverse_Flyes/0.jpg`,
  "Bent Over Lateral Raise":      `${BASE}/Bent-Over_Dumbbell_Rear_Delt_Raise_With_Head_On_Bench/0.jpg`,
  "Reverse Pec Deck":             `${BASE}/Reverse_Flyes/0.jpg`,
  "Upright Row":                  `${BASE}/Barbell_Upright_Row/0.jpg`,
  "Dumbbell Upright Row":         `${BASE}/Dumbbell_Upright_Row/0.jpg`,
  "Cable Upright Row":            `${BASE}/Cable_Upright_Row/0.jpg`,
  "Landmine Lateral Raise":       `${BASE}/Side_Lateral_Raise/1.jpg`,

  // ─── ARMS – BICEPS ───────────────────────────────────────────────────────────
  "Barbell Curl":                 `${BASE}/Barbell_Curl/0.jpg`,
  "EZ Bar Curl":                  `${BASE}/EZ-Bar_Curl/0.jpg`,
  "Preacher Curl":                `${BASE}/Barbell_Preacher_Curl/0.jpg`,
  "EZ Bar Preacher Curl":         `${BASE}/EZ_Barbell_Spider_Curl/0.jpg`,
  "Dumbbell Curl":                `${BASE}/Dumbbell_Alternate_Bicep_Curl/0.jpg`,
  "Incline Dumbbell Curl":        `${BASE}/Alternate_Incline_Dumbbell_Curl/0.jpg`,
  "Concentration Curl":           `${BASE}/Concentration_Curls/0.jpg`,
  "Spider Curl":                  `${BASE}/Spider_Curl/0.jpg`,
  "Hammer Curl":                  `${BASE}/Hammer_Curls/0.jpg`,
  "Cross Body Hammer Curl":       `${BASE}/Cross-Body_Hammer_Curl/0.jpg`,
  "Cable Curl":                   `${BASE}/Cable_Curl/0.jpg`,
  "High Cable Curl":              `${BASE}/High_Cable_Biceps_Curl/0.jpg`,
  "Machine Preacher Curl":        `${BASE}/Lever_Preacher_Curl/0.jpg`,
  "Reverse Curl":                 `${BASE}/Reverse_Barbell_Curl/0.jpg`,
  "Zottman Curl":                 `${BASE}/Zottman_Curl/0.jpg`,

  // ─── ARMS – TRICEPS ──────────────────────────────────────────────────────────
  "Tricep Pushdown":              `${BASE}/Triceps_Pushdown/0.jpg`,
  "Rope Pushdown":                `${BASE}/Triceps_Pushdown_-_Rope_Attachment/0.jpg`,
  "Reverse Grip Pushdown":        `${BASE}/Tricep_Pushdown/0.jpg`,
  "Skull Crusher":                `${BASE}/Barbell_Skull_Crusher/0.jpg`,
  "EZ Bar Skull Crusher":         `${BASE}/EZ-Bar_Skullcrusher/0.jpg`,
  "Dumbbell Skull Crusher":       `${BASE}/Lying_Triceps_Press/0.jpg`,
  "Overhead Tricep Extension":    `${BASE}/Dumbbell_One_Arm_Triceps_Extension/0.jpg`,
  "Barbell Overhead Extension":   `${BASE}/Barbell_Triceps_Extension/0.jpg`,
  "Cable Overhead Extension":     `${BASE}/Cable_Overhead_Triceps_Extension/0.jpg`,
  "Tricep Kickback":              `${BASE}/Dumbbell_Tricep_Kickbacks/0.jpg`,
  "Tricep Dip":                   `${BASE}/Triceps_Dip/0.jpg`,
  "Bench Dip":                    `${BASE}/Bench_Dips/0.jpg`,
  "JM Press":                     `${BASE}/JM_Press/0.jpg`,
  "Machine Tricep Extension":     `${BASE}/Lever_Triceps_Extension/0.jpg`,

  // ─── CORE ────────────────────────────────────────────────────────────────────
  "Plank":                        `${BASE}/Plank/0.jpg`,
  "Side Plank":                   `${BASE}/Side_Plank/0.jpg`,
  "Crunch":                       `${BASE}/Crunch/0.jpg`,
  "Bicycle Crunch":               `${BASE}/Bicycle_Crunch/0.jpg`,
  "Reverse Crunch":               `${BASE}/Reverse_Crunch/0.jpg`,
  "Hanging Leg Raise":            `${BASE}/Hanging_Leg_Raise/0.jpg`,
  "Hanging Knee Raise":           `${BASE}/Hanging_Bent_Knee_Raise/0.jpg`,
  "Toes to Bar":                  `${BASE}/Hanging_Leg_Raise/1.jpg`,
  "Cable Crunch":                 `${BASE}/Cable_Crunch/0.jpg`,
  "Ab Wheel Rollout":             `${BASE}/Ab_Roller/0.jpg`,
  "Russian Twist":                `${BASE}/Russian_Twist/0.jpg`,
  "Weighted Russian Twist":       `${BASE}/Russian_Twist/1.jpg`,
  "V Up":                         `${BASE}/V_Up/0.jpg`,
  "Hollow Body Hold":             `${BASE}/Plank/1.jpg`,
  "Dead Bug":                     `${BASE}/Plank/0.jpg`,
  "Flutter Kicks":                `${BASE}/Flutter_Kicks/0.jpg`,
  "Leg Raise":                    `${BASE}/Flat_Bench_Leg_Pull-In/0.jpg`,
  "Dragon Flag":                  `${BASE}/Dragon_Flag/0.jpg`,
  "Pallof Press":                 `${BASE}/Cable_Woodchop/0.jpg`,
  "Woodchopper":                  `${BASE}/Cable_Woodchop/0.jpg`,
  "Mountain Climber":             `${BASE}/Mountain_Climber/0.jpg`,
  "Sit Up":                       `${BASE}/3_4_Sit-Up/0.jpg`,
  "Decline Sit Up":               `${BASE}/Decline_Crunch/0.jpg`,
  "Ab Machine Crunch":            `${BASE}/Ab_Crunch_Machine/0.jpg`,

  // ─── CARDIO ──────────────────────────────────────────────────────────────────
  "Running":                      `${BASE}/Run/0.jpg`,
  "Treadmill":                    `${BASE}/Jogging,_Treadmill/0.jpg`,
  "Cycling":                      `${BASE}/Bicycling/0.jpg`,
  "Stationary Bike":              `${BASE}/Bicycling,_Stationary/0.jpg`,
  "Rowing Machine":               `${BASE}/Rowing,_Stationary/0.jpg`,
  "Elliptical":                   `${BASE}/Elliptical_Trainer/0.jpg`,
  "Stairmaster":                  `${BASE}/Stairmaster/0.jpg`,
  "Jump Rope":                    `${BASE}/Jump_Rope/0.jpg`,
  "Box Jump":                     `${BASE}/Box_Jump/0.jpg`,
  "Burpee":                       `${BASE}/Burpee/0.jpg`,
  "Jumping Jack":                 `${BASE}/Jumping_Jacks/0.jpg`,
  "High Knees":                   `${BASE}/High_Knee_Jog/0.jpg`,
  "Battle Ropes":                 `${BASE}/Battling_Ropes/0.jpg`,
  "Sled Push":                    `${BASE}/Sled_Push/0.jpg`,
  "Assault Bike":                 `${BASE}/Bicycling,_Stationary/0.jpg`,
  "Swimming":                     `${BASE}/Swimming/0.jpg`,
  "Sprint":                       `${BASE}/Run/0.jpg`,
  "Incline Treadmill Walk":       `${BASE}/Jogging,_Treadmill/1.jpg`,

  // ─── OTHER / FULL BODY ───────────────────────────────────────────────────────
  "Power Clean":                  `${BASE}/Power_Clean/0.jpg`,
  "Hang Clean":                   `${BASE}/Hang_Clean/0.jpg`,
  "Clean and Jerk":               `${BASE}/Clean_and_Jerk/0.jpg`,
  "Snatch":                       `${BASE}/Snatch/0.jpg`,
  "Kettlebell Swing":             `${BASE}/Kettlebell_Figure_8/0.jpg`,
  "Kettlebell Clean":             `${BASE}/Alternating_Hang_Clean/0.jpg`,
  "Kettlebell Press":             `${BASE}/Alternating_Kettlebell_Press/0.jpg`,
  "Turkish Get Up":               `${BASE}/Turkish_Get-up_-_Snatch_Grip_-_Bottom_Up/0.jpg`,
  "Farmers Walk":                 `${BASE}/Farmers_Walk/0.jpg`,
  "Suitcase Carry":               `${BASE}/Farmers_Walk/0.jpg`,
  "Bear Hug Carry":               `${BASE}/Tire_Flip/0.jpg`,
  "Thruster":                     `${BASE}/Barbell_Thruster/0.jpg`,
  "Medicine Ball Slam":           `${BASE}/Medicine_Ball_Slam/0.jpg`,
  "Wall Ball":                    `${BASE}/Wall_Ball_Shots/0.jpg`,
  "Battle Ropes Waves":           `${BASE}/Battling_Ropes/0.jpg`,
};

export function getExerciseImageUrl(exerciseName: string): string | null {
  return EXERCISE_IMAGE_MAP[exerciseName] ?? null;
}

export const EXERCISE_IMAGE_FALLBACK_COLORS: Record<string, string> = {
  Chest:     "bg-red-500/20",
  Back:      "bg-blue-500/20",
  Legs:      "bg-green-500/20",
  Shoulders: "bg-yellow-500/20",
  Arms:      "bg-purple-500/20",
  Core:      "bg-orange-500/20",
  Cardio:    "bg-pink-500/20",
  Other:     "bg-muted",
};
