import { z } from "zod";

export const mutualFundFormSchema = z.object({
  name: z
    .string()
    .min(1, "Fund name is required")
    .max(100, "Name must be less than 100 characters"),
  symbol: z
    .string()
    .min(1, "Symbol is required")
    .max(20, "Symbol must be less than 20 characters"),
  investedAmount: z.number().min(0, "Invested amount cannot be negative"),
  units: z.number().min(0.01, "Units must be greater than 0"),
  nav: z.number().min(0.01, "NAV must be greater than 0"),
  purchaseNav: z.number().min(0.01, "Purchase NAV must be greater than 0"),
  currentValue: z.number().min(0, "Current value cannot be negative"),
  purchaseDate: z.string().optional(),
  category: z.enum([
    "equity",
    "debt",
    "hybrid",
    "index",
    "international",
    "other",
  ]),
  subCategory: z.enum([
    "large_cap",
    "large_mid_cap",
    "mid_cap",
    "small_cap",
    "flexi_cap",
    "multi_cap",
    "focused_fund",
    "index_fund",
    "contra_fund",
    "value_fund",
    "sectoral_service",
    "sectoral_pharma",
    "sectoral_consumption",
    "elss",
    "thematic_mnc",
    "sectoral_infrastructure",
    "thematic_global",
    "sectoral_banks",
    "sectoral_technology",
    "dividend_yield",
    "sectoral_energy",
    "sectoral_auto",
    "thematic_fund",
    "floating_rate",
    "banking_psu",
    "fixed_maturity",
    "ultra_short_duration",
    "overnight",
    "money_market",
    "dynamic_bond",
    "credit_risk",
    "corporate_bond",
    "liquid",
    "low_duration",
    "gilt_long_term",
    "medium_duration",
    "long_duration",
    "short_duration",
    "medium_to_long_duration",
    "gilt_short_mid_term",
    "debt_interval",
    "index_debt_oriented",
    "sectoral_infrastructure_debt",
    "arbitrage",
    "multi_asset_allocation",
    "balanced_advantage",
    "aggressive_hybrid",
    "dynamic_asset_allocation",
    "equity_savings",
    "conservative_hybrid",
    "balanced_hybrid",
    "other",
  ]),
});

export type MutualFundFormData = z.infer<typeof mutualFundFormSchema>;
